FROM python:3.11-slim AS builder
WORKDIR /app
COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install --prefix=/install kafka-python==2.0.2

FROM python:3.11-slim
WORKDIR /app
COPY --from=builder /install /usr/local
RUN mkdir -p /app/data
COPY archiver.py .
VOLUME ["/app/data"]
CMD ["python", "archiver.py"]